### ISSUE TITLE
Time shift 1 hour with Apple Calendar

### ISSUE THREAD

**Issue by MaximIgenbergs** [TUM-Dev/CalendarProxy#127]
Hi, my normal tum cal subscription works fine, but with this proxy everything is one hour earlier...

**Comment by joschahenningsen** [comment]
What's your timezone? [CET](https://time.is/CET)?

**Comment by joschahenningsen** [comment]
Also which client do you use to display your calendar?

**Comment by MaximIgenbergs** [comment]
apple calendar, timezone: berlin (CET)
benutze das proxy seit über einem jahr, am freitag hat es noch funktioniert...

**Comment by joschahenningsen** [comment]
Likely related to #126, ping @kordianbruck

**Comment by kordianbruck** [comment]
Ja, crap. Wenn ich das timezone Handling dazu packe, dann geht die library out of memory.

**Comment by mariusdkm** [comment]
Hab des gleiche Problem, dass alle TUM Termine um 1h in der Zukunft liegen.
(Auf in der Calendar App in MacOS und in der Google Calendar App auf Android).
Der Originale TUM Kalender ist noch richtig.

**Comment by rogerters** [comment]
Same here, leider!

**Comment by kordianbruck** [comment]
Should be fixed! Verified by subscribing to a few calendars myself.

Note that Google Calendar and others might cache the calendar for several days. Recreating it sometimes does not help, but you can add `&test=1` to the end of the URL to force a refresh. Sorry for all the troubles! 

(Please do confirm if its fixed for you)

**Comment by nwormek** [comment]
I also still have the same problem (on Apple Calendar) even after adding `&test=1`

**Comment by kordianbruck** [comment]
What type of calendar software are you using? Please send me your personal link via Email, then I can go and test it with your data.

**Comment by kordianbruck** [comment]
Also please test it with something else than Apple Calendar if you can to confirm that its only Apple Calendar that is currently affected.

**Comment by MaximIgenbergs** [comment]
google calendar works fine

**Comment by j4n-k** [comment]
> Also please test it with something else than Apple Calendar if you can to confirm that its only Apple Calendar that is currently affected.
Yes, this is still an issue for Apple Calendar

**Comment by nwormek** [comment]
> Also please test it with something else than Apple Calendar if you can to confirm that its only Apple Calendar that is currently affected.

I also tested it with Gnome Calendar on Linux, same problem.

**Comment by MaximIgenbergs** [comment]
how long do you think its going to be until fixed?

**Comment by MaximIgenbergs** [comment]
updates?

**Comment by aGuyLearning** [comment]
Could we reopen this, as it is still not resolved for apple calendar

**Comment by joschahenningsen** [comment]
@kordianbruck should we revert the commit(s) that broke this until we have a fix?

**Comment by MaximIgenbergs** [comment]
pls

**Comment by kordianbruck** [comment]
Yes, anything but Apple Calendar seems to work at this point. 

> I also tested it with Gnome Calendar on Linux, same problem.

I've tried it today, works fine as well.

For the love of God, I can't figure out what is wrong supposedly with the ical files, that Apple Calendar parses the timezones wrong for this. I've looked through all the parts in the library that generates these timestamps, but I'm still not actually sure what is wrong: https://github.com/markuspoerschke/iCal (There are aren't any bugs or problems reported upstream)

Sooooo, if anyone has an idea, feel free to propose a pull request. I'm all out of ideas.

**Comment by kordianbruck** [comment]
> revert the commit(s)

the problem is that the old library versions are no longer compatible with PHP 8.X, so that isn't an option now that [PHP 7.4](https://www.php.net/supported-versions.php) is no longer supported.

**Comment by joschahenningsen** [comment]
I started a rewrite: https://github.com/TUM-Dev/CalendarProxy/tree/v2

Please test if the calendar looks about right if you replace the `cal.bruck.me` part of the url with `cal.joschas.page`. Your link should look like this: 
`https://cal.joschas.page/?pStud=1234ABCD&pToken=12345678ABCDEF`

Let me know about any problems with this, I'm sure there are some.

**Comment by nwormek** [comment]
I tried it, and it fixes the time shift issue, but doesn't combine parallel events.

**Comment by joschahenningsen** [comment]
@nwormek good hint, I don't have a calendar with duplication for testing. I tried something, does it work now?

**Comment by nwormek** [comment]
Yes, now it works 👍

**Comment by MaximIgenbergs** [comment]
Yess it works thank you so much !!!
